### ISSUE TITLE
Improve readme

### ISSUE THREAD

**Issue by planger** [eclipse-cdt-cloud/vscode-memory-inspector#103]
The README is currently not focused on attracting users and also contains two broken links (see below).
For making it more attractive for users I suggest to:
- Add a screenshot to the README showing off the basic functionality
- Add a list of features
- Point to configurations

Broken links:
- https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/blob/main/src/webview/components/memory-widget.ts
- https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/blob/main/src/webview/components/table.tsx

**Comment by jreineckearm** [comment]
@planger , I think we can close this one now :-)
