### ISSUE TITLE
Implement automatic update when frame changes

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-cdt-cloud/vscode-memory-inspector#11]
At present, new memory is only fetched when a user opens a new view or explicitly clicks the `Go` button in a given view. It might be convenient to have the view update automatically when a session's state changes.

This feature raises questions:
 - To what sort of events should the view respond? Only to step on same thread? Any change?
 - How configurable should the behavior be, and what are the important parameters for configuration?

**Comment by thegecko** [comment]
IMO a good start would be to hook into the stopped event
