### ISSUE TITLE
Refactor existing CSS in JS to use external stylesheets

### ISSUE THREAD

**Issue by kenneth-marut-work** [eclipse-cdt-cloud/vscode-memory-inspector#35]
**Description**

As of #28, we are currently using both external CSS stylesheets as well as CSS in JS as style tags to React components. All CSS should be refactored to use external stylesheets for consistency, and because CSS in JS has limitiations (e.g. :hover pseudo-class can't be implemented without external libraries).

**Comment by colin-grant-work** [comment]
Fixed by https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/pull/37
