### ISSUE TITLE
Adjusting display parameters misaligns columns

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-cdt-cloud/vscode-memory-inspector#38]
**Description**

Adjusting the grouping parameters in the view can cause some columns to become misaligned. Typically occurs when variables are visible already and variable names have different lengths.

**How to reproduce:**

1. Reveal the variables column
2. Adjust the grouping settings
3. Observe that column alignment breaks.

**Expected behavior**

1. The column contents should align with one another.

**Environment**
 - _OS_: RHEL7
 - _Browser_: Desktop
 - _Theia or VS Code Version_: VSCode 1.81

**Additional information**

![image](https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/assets/62660806/7c8d35e4-8e47-4c0c-8bca-f0290edf49fd)

**Comment by kenneth-marut-work** [comment]
Some initial investigation shows that the `grid-template-columns` value that is actually rendered in the DOM is inconsistent from the value that we are seeing in React. It seems that there is some sort of fallback (for lack of a better word) value of `1fr 1fr` that appears when the columns are misaligned and I'm not sure where it's coming from. In my tests, I've changed the string value for the grid template columns to use the `repeat` syntax, and so as far as I know, there should be no way of rendering the value `1fr 1fr`.

**UNEXPECTED VALUE**
![image](https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/assets/62660714/ed404b14-d597-4caa-b379-fd2ed59ee68b)

**EXPECTED VALUE**
![image](https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/assets/62660714/fa56c5ad-2eff-48ec-a5b1-89c73e6d7c29)

**Comment by jreineckearm** [comment]
To share another reproducer:
* Reveal the variables column
* Edit the address field and press "Go"
* Column alignments can break.
* Click "Go" with the same address value => Alignments are fixed again
