### ISSUE TITLE
Load/Save memory content

### ISSUE THREAD

**Issue by jreineckearm** [eclipse-cdt-cloud/vscode-memory-inspector#50]
**Description**

It would be a powerful feature to save and load memory contents. This data could be stored in a variety of formats. For example Intel Hex format or plain binary.

**Additional information**

**Comment by planger** [comment]
From a discussion offline:
* Users should be able to specify start address and size when triggering the save. The pre-filled values should correspond to what the user has specified in the memory view instance.
* When loading back from file, the memory for the address range should be written back into the memory of the debug target.
