### ISSUE TITLE
Automatically append new memory window content when scrolling to bottom of available data

### ISSUE THREAD

**Issue by jreineckearm** [eclipse-cdt-cloud/vscode-memory-inspector#56]
**Description**

A nice usability enhancement for the Memory Inspector navigation would be to allow automatically appending new memory contents when reaching the bottom of the vertical scrollbar. The new load could be based on the configured `length`.

The Memory Inspector already has the ability to load additional memory content. But this currently requires an extra click on the link/button at the bottom of the view. So, an automatism could be beneficial to avoid this extra click.

The proposal at this stage is to reflect the new scroll-mode by a new selection in the `memory-inspector.scrollingBehavior` setting.
This could be called `automatic` or something similar. In that way, the existing scroll-mode behavior could be preserved.

The growing memory content buffer would be cleared by a subsequent click on the `Go` button.

**Additional information**

**Comment by martin-fleck-at** [comment]
I really like the idea of automatically expanding the memory when scrolling down! I also believe that having it as a third option might be the most sensical approach.

Just for a little bit of context, we currently have the following Scrolling Behavior:
- `Paginate`: Maintains a consistent memory size, replacing the previous request, i.e., it is replacing the current memory with the newly loaded one by manipulating the `offset`, see https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/blob/f611578e8cec1e9a7130d77ae95744e96ab37397/src/webview/components/memory-table.tsx#L58.
- `Infinite`: Appends new memory to bounds of current request, resulting in a growing list by manipulating the `count` but keeping the offset stable, see https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/blob/f611578e8cec1e9a7130d77ae95744e96ab37397/src/webview/components/memory-table.tsx#L55

While for me conceptually, there is a distinction between append/replace (how to load memory) and select/scroll (how to trigger memory loading), having a third option in the existing setting is probably the best idea as the scroll behavior only makes sense when we actually append memory and also only ever in one direction (below, scrolling down) so introducing yet another setting may be confusing.

I also like the name `Automatic` even though personally I feel that the name `Infinite` represents a bit better what we are doing but that is already taken. However, as all options have some description anyway, any confusion can be cleared up there. Does anybody know where those original names come from and whether it makes sense to revise them in light of a third option?

**Comment by jreineckearm** [comment]
@martin-fleck-at , looking through the commit history, changes around the scrolling behavior were introduced by @kenneth-marut-work and @colin-grant-work . I appreciate that `Automatic` could be too generic. `Infinite` would be a better match. But as you mention it's in use already and we should try to avoid removing existing behavior. What about `Continuous`?

**Comment by colin-grant-work** [comment]
> only ever in one direction (below, scrolling down)

Usually, scrolling up is equally possible :-).

The model from which we derived the current state of the Memory Inspector did allow infinite scroll, but we found the UX not to be very good, so we opted for the style currently available, but others' preferences may vary, so I'm not opposed to offering an infinite scroll option.

**Comment by jreineckearm** [comment]
> Usually, scrolling up is equally possible :-).

Fair point. :-)
We had good experience in the past with only downwards scrolling in other tools. This helped to preserve the starting point. Assuming that the user adjusts this consciously by updating the `address` field. But I see the charm of having a supported way of peeking into memory before the start address. For example if you have a stack pointer value and would like to inspect the previously used stack memory. I think a mixture of automatically loading on a down-scroll and preserving the option to load memory before as in the current model would be best for such a new scroll mode.

@colin-grant-work , your feedback shows me that we definitely need to preserve the existing scroll models as option. This seems to have a user base already.

I guess this leaves us with the naming challenge for the new mode. :-)

**Comment by martin-fleck-at** [comment]
> 
> Usually, scrolling up is equally possible :-).
>

Good point! In my mind I was tying it to loading without user interaction, i.e., as soon as the top is visible we load more data, leading to data constantly being loaded but that is of course not how that should work. I'm still worried it might lead to a strange user interaction if that is triggered too easily but maybe that concern is unwarranted and just needs to be tested if we really want the scrolling up mechanism.

> 
> I guess this leaves us with the naming challenge for the new mode. :-)
>

Finding a good name is indeed a challenge! Since the setting itself is already called `Scrolling Behavior`, anything with "scrolling" in the name will probably add more confusion. The longer I think about, the more I actually like `Automatic` as what we actually do is automatically scroll the memory with the mouse wheel. `Continuous` may be more correct but to me personally it feels weird as an option. Alternatively something as plain as `Mouse Wheel` or `Wheel` could also be considered.

**Comment by jreineckearm** [comment]
Other options for the name could be `Append`, `Auto-Append`, or something along those lines.
`Wheel` might be confusing because you still can scroll through the loaded content with the mouse wheel in the other modes.

**Comment by martin-fleck-at** [comment]
What would be the best option to settle this? We currently have the following proposals:
- `Automatic`
- `Auto-Append`
- `Continuous`
- `Append`

Anyone else who wants to chime in? So far, I'd cast my vote for `Automatic`.

**Comment by jreineckearm** [comment]
Thanks for coming back to this. I am in favor of `Automatic` or `Auto-Append`. With a slight tendency towards `Auto-Append`.

**Comment by martin-fleck-at** [comment]
> And that I see this to remain a separate scroll model even if we should decide for a full `Automatic` mode that also prepends data in future.

With this in mind, I also lean slightly towards `Auto-Append`, I previously assumed that we will extend to auto-append to automatic but if they are separate modes then we should definitely choose the more specific name now.
