### ISSUE TITLE
Allow display configurations per Memory Inspector view instance

### ISSUE THREAD

**Issue by planger** [eclipse-cdt-cloud/vscode-memory-inspector#60]
### Current implementation
When a user modifies the configuration (display options) in a specific Memory Inspector view, these changes update the VS Code settings and apply to all open Memory Inspector views. This behavior might be unexpected for users. Also it prevents users from specifying different configurations in separate views.

### Suggestion
1. A new memory view is opened with the display configuration as defined in the VS Code settings.
2. Changes made to the local options in a view affect only the specific view where the changes were made.
3. Altering global settings in the VS Code prefs doesn't impact any already open views.
4. Optional addition: There is a button in the local options to reset to defaults, which applies the configuration as defined in the VS Code settings.

**Comment by jreineckearm** [comment]
Proposed behavior sounds sensible to me.
