### ISSUE TITLE
Enhance Memory Address Formatting in Memory Inspector

### ISSUE THREAD

**Issue by planger** [eclipse-cdt-cloud/vscode-memory-inspector#62]
Introduce a new feature to the Memory Inspector that enhances memory address formatting by providing user settings for base prefix visibility and address format customization.

* **Base Prefix Visibility Toggle**:<br>Introduce a user setting allowing for the toggling of base prefixes in memory values display (e.g., `0`, `0x`, etc.).
* **Memory Address Format Customization**:<br>Add a user setting to customize the format of memory addresses, specifically allowing for changes in radix (e.g., Hex, Oct, etc.).

According to how it is specified in https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/issues/60, the default values of both settings above should be defined in the VS Code settings, and can be adjusted by the user in each Memory Inspector view independently.

**Comment by jreineckearm** [comment]
Eventually, a quick access to the local window setting could also be made available through a context menu entry.
