### ISSUE TITLE
Allow to configure word size

### ISSUE THREAD

**Issue by planger** [eclipse-cdt-cloud/vscode-memory-inspector#74]
**Description**
Currently the size of a word is fixed to one byte. Add a option for users to change the word size. This user option shall be changeable per memory view instance and the default value shall be specified with a VS Code setting (similar to the settings introduced in https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/issues/60).

To clarify the options, we should probably rename the existing option "Bytes per Group" to "Words by Group". This gives the user the following options:
* Bytes per word (the hover feature will use that scope)
* Words per group (groups are separated by a [horizontal margin](https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/issues/75) to guide reading)
* Groups per row (determines the width of a row)

**Additional information**
In the Theia Memory Inspector, this setting seems to be called "Byte Size".

**Comment by planger** [comment]
@colin-grant-work As the terminology proposed above diverges from the one in the Theia Memory Inspector and may impact the hover feature (in terms of its scope), I'd like to get your opinion on the proposal above. Please let us know what you think. Thank you!

**Comment by colin-grant-work** [comment]
Your description sounds reasonable. The only thing I would add would be what I said in [this comment](https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/issues/48#issuecomment-1942394325), namely that it would be desirable for the wordsize to be retrievable from an `AdapterCapabilities` implementation that knows how to get it for a given debug adapter / debug session.

**Comment by jreineckearm** [comment]
Agree with @colin-grant-work , best might be an `auto` or other named selection triggering this. Should probably default to `1` if not provided from extern.

**Comment by colin-grant-work** [comment]
> I'd like to clarify what you mean by `AdapterCapabilities`

I'm referring to [this interface](https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/blob/bc14fefc7704b31e7cf0529b324368c19742845e/src/plugin/adapter-registry/adapter-capabilities.ts#L23) that allows us to contribute functionality that goes beyond the DAP for specific debug adapters.

**Comment by planger** [comment]
> > I'd like to clarify what you mean by `AdapterCapabilities`
> 
> I'm referring to [this interface](https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/blob/bc14fefc7704b31e7cf0529b324368c19742845e/src/plugin/adapter-registry/adapter-capabilities.ts#L23) that allows us to contribute functionality that goes beyond the DAP for specific debug adapters. It's currently used primarily for variable retrieval, but we can expand its interface if there are other pieces of functionality beyond the DAP that we're interested in.

Ah, great, got it. Thank you!
